version: "3.7"

x-env: &env
  NAME: "transactions"
  NETWORK_NAME: "mainnet"

  # Ports
  PORT: "8000"
  HEALTH_PORT: "8180"
  METRICS_PORT: "9400"

  # Prefix
  REST_PREFIX: "/api/v1"
  WEBSOCKET_PREFIX: "/ws/v1"
  HEALTH_PREFIX: "/heath"
  METRICS_PREFIX: "/metrics"

  # Monitoring
  HEALTH_POLLING_INTERVAL: "60"

  # Logging
  LOG_LEVEL: "DEBUG"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: "transactions.log"
  LOG_FORMAT: "string"

  # Kafka
  KAFKA_BROKER_URL: "kafka:9092"
  SCHEMA_REGISTRY_URL: "schemaregistry:8081"
  KAFKA_GROUP_ID: "transactions-service"

  # Topics
  SCHEMA_NAME_TOPICS: "transactions-ws:transactions"
  SCHEMA_FOLDER_PATH: "/app/schemas/"

  # DB
  DB_DRIVER: "mongodb"
  DB_HOST: "mongo"
  DB_PORT: "27017"
  DB_USER: "mongo"
  DB_PASSWORD: "changethis"
  DB_DBNAME: "local"
  DB_SSLMODE: "disable"
  DB_TIMEZONE: "UTC"

services:
  transactions-api:
    build:
      context: ${TRANSACTIONS_CONTEXT:-.}
      target: ${TRANSACTIONS_TARGET:-prod}
      args:
        - SERVICE_NAME=api
    ports:
      - "8000:8000"     # API
      - "8180:8180"     # Health
      - "9400:9400"     # Prometheus
      - "40000:40000"   # Remote Debug
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${TRANSACTIONS_CONTEXT:-.}/src:/app
    environment:
      <<: *env
      CONSUMER_TOPICS: "transactions-ws"

  transactions-worker:
    build:
      context: ${TRANSACTIONS_CONTEXT:-.}
      target: ${TRANSACTIONS_TARGET:-prod}
      args:
        - SERVICE_NAME=worker
    ports:
      - "8181:8181"     # Health
      - "9401:9401"     # Prometheus
      - "40001:40001"   # Remote Debug
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${TRANSACTIONS_CONTEXT:-.}/src:/app
    environment:
      <<: *env
      CONSUMER_TOPICS: "transactions,logs"
      PRODUCER_TOPICS: "transactions-ws"
